---
openapi: 3.0.3
info:
  title: Test API
  version: 0.0.1
tags:
  - name: testApi
paths:
  /upload-file-and-json:
    post:
      tags:
        - testApi
      operationId: uploadFileAndJson
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                someObject:
                  $ref: '#/components/schemas/SomeObject'
                image:
                  type: string
                  format: binary
              required:
                - image
                - someObject
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SomeResponse'
components:
  schemas:
    SomeObject:
      type: object
      properties:
        description:
          type: string
      required:
        - description
    SomeResponse:
      type: object
      properties:
        type:
          type: string
          enum:
            - success
            - failure
